version: '2'
networks:
  default:
    name: t-dat-901-network

services:
  zookeeper:
    container_name: t-dat-901-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - default

  kafka:
    container_name: t-dat-901-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: t-dat-901-zookeeper:2181
    networks:
      - default

  kowl:
    container_name: t-dat-901-kowl
    image: rsmnarts/kowl:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://host.docker.internal:9092
      KAFKA_BROKERS: host.docker.internal:9092
      WAIT_FOR_KAFKA: "true"
    depends_on:
      - kafka
    networks:
      - default