version: '3.3'

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

services:

  # Cassandra
  cassandra-service:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./cnf/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra:/var/lib/cassandra
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      app_net:
        ipv4_address: 172.16.238.13
