cluster_name: 'tdat901'
commitlog_sync: batch
listen_address: 172.28.0.6
rpc_address: 0.0.0.0
broadcast_rpc_address: 172.28.0.6
endpoint_snitch: GossipingPropertyFileSnitch
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
         - seeds: "172.28.0.6"

partitioner: org.apache.cassandra.dht.Murmur3Partitioner
