cluster_name: 'tdat901'
commitlog_sync: batch
listen_address: 172.18.0.8
rpc_address: 0.0.0.0
broadcast_rpc_address: 172.18.0.8
endpoint_snitch: GossipingPropertyFileSnitch
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
         - seeds: "172.18.0.8"

partitioner: org.apache.cassandra.dht.Murmur3Partitioner
