cluster_name: 'tdat901'
commitlog_sync: batch
listen_address: 192.168.208.5
rpc_address: 0.0.0.0
broadcast_rpc_address: 192.168.208.5
endpoint_snitch: GossipingPropertyFileSnitch
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
         - seeds: "192.168.208.5"
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
